// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Airdrop: typeof import('./src/components/airdrop/index.vue')['default']
    Empty: typeof import('./src/components/empty/index.vue')['default']
    FallingGif: typeof import('./src/components/FallingGif/index.vue')['default']
    InviteOverlay: typeof import('./src/components/invite-overlay/index.vue')['default']
    NoInvite: typeof import('./src/components/no-invite/index.vue')['default']
    Notify: typeof import('./src/components/notify/index.vue')['default']
    Overlay: typeof import('./src/components/overlay/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Rule: typeof import('./src/components/rule/index.vue')['default']
    StartPopup: typeof import('./src/components/start-popup/index.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanField: typeof import('vant/es')['Field']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanLoading: typeof import('vant/es')['Loading']
    VanOverlay: typeof import('vant/es')['Overlay']
    VanPopover: typeof import('vant/es')['Popover']
    VanPopup: typeof import('vant/es')['Popup']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
    VanTab: typeof import('vant/es')['Tab']
    VanTabs: typeof import('vant/es')['Tabs']
    VanToast: typeof import('vant/es')['Toast']
  }
}
